version: '3.9'

services:
  ExtrairInformacoesDosDocumentosTask:
    image: camworker
    hostname: ExtrairInformacoesDosDocumentosTask
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - TOPIC=ExtrairInformacoesDosDocumentosTask
      - ENG_REST_URL=${CAMUNDA_URL}
      - ENG_REST_USERNAME=${CAMUNDA_USERNAME}
      - ENG_REST_PASSWORD=${CAMUNDA_PASSWORD}
      - MAX_TASK_DURATION=30000
      - FINAN_HOST_DB=${FINAN_HOST_DB}
      - FINAN_PORT_DB=${FINAN_PORT_DB}
      - FINAN_USER_DB=${FINAN_USER_DB}
      - FINAN_PASSWD_DB=${FINAN_PASSWD_DB}
      - FINAN_DB=${FINAN_DB}
      - FINAN_FTP_HOST=${FINAN_FTP_HOST'}
      - FINAN_FTP_USER=${FINAN_FTP_USER'}
      - FINAN_FTP_PASSWD=${FINAN_FTP_PASSWD'}

networks:
  default:
    external: true
    name: backend